spring.data.redis.host=localhost
spring.data.redis.port=6379

posheet.storage.endpoint=http://localhost:9000
posheet.storage.access-key=minioadmin
posheet.storage.secret-key=minioadmin
posheet.storage.region=us-east-1
