spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

posheet.storage.access-key=${AWS_ACCESS_KEY}
posheet.storage.secret-key=${AWS_SECRET_KEY}
posheet.storage.region=ap-northeast-2
